### ISSUE TITLE
Assignment 7

### ISSUE THREAD

**Issue by alopp18** [alopp18/assignment-7#1]
In assignment 7, we were tasked with writing a short description on a R package that we consider important or one that we often use in our own work. In the read-me file, you can my description of ggplot2. While this is a very common package, it is one that I find very useful as a novice programmer. Hopefully, I can use other examples from my peers to enhance my knowledge of what is available to better my skills!

**Comment by mdscheuerell** [comment]
Nice overview of `{ggplot2}`!
